-- Additional client portal form questions for WS1 + WS2 agents.
-- Safe to run multiple times.

INSERT INTO "AgentFormQuestion"
  ("id", "agentId", "agentName", "fieldKey", "label", "description", "inputType", "placeholder", "required", "options", "groupKey", "groupLabel", "sortOrder", "isActive")
VALUES
  ('pricing_vertical_businessWebsite', 'pricing_vertical', 'Pricing by Vertical Agent', 'businessWebsite', 'Business website', 'Main business website or pricing/services page used to scrape current service prices.', 'url', 'https://yourbusiness.com/pricing', true, NULL, 'business', 'Business Information', 10, true),

  ('facility_review_businessAddress', 'facility_review', 'Facility Review Agent', 'businessAddress', 'Facility address / location', 'Physical location used for the facility review context.', 'text', '760 Terminal Ave, Vancouver, BC', true, NULL, 'facility_review_overview', 'Facility Review - Overview', 150, true),
  ('facility_review_facilityExteriorLastPainted', 'facility_review', 'Facility Review Agent', 'facilityExteriorLastPainted', 'When was the exterior last painted or pressure-washed?', 'Month and year, e.g. Spring 2023, full repaint.', 'text', 'Spring 2023, full repaint', true, NULL, 'facility_review_exterior', 'Zone 1 - Exterior & Curb Appeal', 160, true),
  ('facility_review_facilityExteriorRepairs', 'facility_review', 'Facility Review Agent', 'facilityExteriorRepairs', 'Are there any outstanding exterior repairs, bylaw violations, or open permits?', 'List each item. If none, write None.', 'textarea', 'None', true, NULL, 'facility_review_exterior', 'Zone 1 - Exterior & Curb Appeal', 161, true),
  ('facility_review_facilityReceptionLastRefreshed', 'facility_review', 'Facility Review Agent', 'facilityReceptionLastRefreshed', 'When was the reception area last renovated, repainted, or meaningfully refreshed?', NULL, 'text', 'Repainted in 2024; flooring replaced in 2022', true, NULL, 'facility_review_reception', 'Zone 2 - Reception', 170, true),
  ('facility_review_facilityReceptionRetail', 'facility_review', 'Facility Review Agent', 'facilityReceptionRetail', 'Is retail product sold in this area? If so, what categories?', NULL, 'textarea', 'Food, treats, leashes, toys, grooming products...', true, NULL, 'facility_review_reception', 'Zone 2 - Reception', 171, true),
  ('facility_review_facilityKennelPanels', 'facility_review', 'Facility Review Agent', 'facilityKennelPanels', 'What material are the kennel panels made of? When were they last replaced or refinished?', 'Note if different tiers are in different condition.', 'textarea', 'Stainless steel panels, refinished 2021. Premium suites replaced 2023.', true, NULL, 'facility_review_boarding', 'Zone 3 - Boarding', 180, true),
  ('facility_review_facilityHvacLastServiced', 'facility_review', 'Facility Review Agent', 'facilityHvacLastServiced', 'When was the HVAC system last professionally serviced?', 'Month / year of last service.', 'text', 'March 2025', true, NULL, 'facility_review_boarding', 'Zone 3 - Boarding', 181, true),
  ('facility_review_facilityHvacServiceRecord', 'facility_review', 'Facility Review Agent', 'facilityHvacServiceRecord', 'Is an HVAC service record available?', NULL, 'select', NULL, true, '["Yes","No"]'::jsonb, 'facility_review_boarding', 'Zone 3 - Boarding', 182, true),
  ('facility_review_facilityBoardingMaintenanceIssues', 'facility_review', 'Facility Review Agent', 'facilityBoardingMaintenanceIssues', 'Are there any known maintenance issues in the boarding zone not visible in photos?', 'If none, write None.', 'textarea', 'None', true, NULL, 'facility_review_boarding', 'Zone 3 - Boarding', 183, true),
  ('facility_review_facilityGroomingStationCount', 'facility_review', 'Facility Review Agent', 'facilityGroomingStationCount', 'How many grooming stations does the suite have?', NULL, 'number', '3', true, NULL, 'facility_review_grooming', 'Zone 4 - Grooming', 190, true),
  ('facility_review_facilityGroomingTableDetails', 'facility_review', 'Facility Review Agent', 'facilityGroomingTableDetails', 'What type of grooming tables are in use and how old are they?', NULL, 'textarea', '2 hydraulic lift tables, purchased 2023. 1 fixed table, approx. 8 years old.', true, NULL, 'facility_review_grooming', 'Zone 4 - Grooming', 191, true),
  ('facility_review_facilityDryerDetails', 'facility_review', 'Facility Review Agent', 'facilityDryerDetails', 'What dryers are in use? When were they last replaced or serviced?', NULL, 'textarea', 'Two stand dryers serviced 2024; one cage dryer purchased 2022.', true, NULL, 'facility_review_grooming', 'Zone 4 - Grooming', 192, true),
  ('facility_review_facilityGroomingVentilation', 'facility_review', 'Facility Review Agent', 'facilityGroomingVentilation', 'Does the grooming suite have dedicated ventilation?', NULL, 'select', NULL, true, '["Yes - dedicated system","Shared with rest of facility","No ventilation system"]'::jsonb, 'facility_review_grooming', 'Zone 4 - Grooming', 193, true),
  ('facility_review_facilityIndoorPlayAreaCount', 'facility_review', 'Facility Review Agent', 'facilityIndoorPlayAreaCount', 'How many indoor play areas does the facility operate?', NULL, 'number', '2', true, NULL, 'facility_review_indoor_play', 'Zone 5 - Indoor Play', 200, true),
  ('facility_review_facilityIndoorPlayIssues', 'facility_review', 'Facility Review Agent', 'facilityIndoorPlayIssues', 'Are there any known maintenance or condition issues in indoor play areas not visible in photos?', 'If none, write None.', 'textarea', 'None', true, NULL, 'facility_review_indoor_play', 'Zone 5 - Indoor Play', 201, true),
  ('facility_review_facilityOutdoorFencing', 'facility_review', 'Facility Review Agent', 'facilityOutdoorFencing', 'What is the fencing type and approximate age across all yards?', 'Note differences between yards if relevant.', 'textarea', 'Large yard: chain-link 2016. Puppy yard: wood panel 2021.', true, NULL, 'facility_review_outdoor_play', 'Zone 6 - Outdoor Play', 210, true),
  ('facility_review_facilityOutdoorShade', 'facility_review', 'Facility Review Agent', 'facilityOutdoorShade', 'Is there a permanent shade structure in any yard?', NULL, 'select', NULL, true, '["Yes - all yards","Yes - some yards","Portable / seasonal only","No shade structure"]'::jsonb, 'facility_review_outdoor_play', 'Zone 6 - Outdoor Play', 211, true),
  ('facility_review_facilityOutdoorWaterSource', 'facility_review', 'Facility Review Agent', 'facilityOutdoorWaterSource', 'Is there a permanent water source in the outdoor area?', NULL, 'select', NULL, true, '["Yes - permanent fixture","Yes - hose access only","No"]'::jsonb, 'facility_review_outdoor_play', 'Zone 6 - Outdoor Play', 212, true),
  ('facility_review_facilityOutdoorIssues', 'facility_review', 'Facility Review Agent', 'facilityOutdoorIssues', 'Are there any known fencing, surface, or structural issues not visible in photos?', 'If none, write None.', 'textarea', 'None', true, NULL, 'facility_review_outdoor_play', 'Zone 6 - Outdoor Play', 213, true),
  ('facility_review_facilityLaundrySetup', 'facility_review', 'Facility Review Agent', 'facilityLaundrySetup', 'Is there a dedicated laundry setup on-site?', NULL, 'select', NULL, true, '["Yes - commercial units","Yes - residential units","No on-site laundry"]'::jsonb, 'facility_review_staff_ops', 'Zone 7 - Staff & Operational Areas', 220, true),
  ('facility_review_facilityLaundryUnitAge', 'facility_review', 'Facility Review Agent', 'facilityLaundryUnitAge', 'If laundry units are present, what is their approximate age?', NULL, 'text', 'Commercial washer/dryer, approx. 4 years old', true, NULL, 'facility_review_staff_ops', 'Zone 7 - Staff & Operational Areas', 221, true),
  ('facility_review_facilityOperationalIssues', 'facility_review', 'Facility Review Agent', 'facilityOperationalIssues', 'Are there any known operational or facilities issues in this zone not visible in photos?', 'If none, write None.', 'textarea', 'None', true, NULL, 'facility_review_staff_ops', 'Zone 7 - Staff & Operational Areas', 222, true),
  ('facility_review_facilityBusinessLicenseExpiry', 'facility_review', 'Facility Review Agent', 'facilityBusinessLicenseExpiry', 'Business license expiry date', 'Month / year.', 'text', 'December 2026', true, NULL, 'facility_review_compliance', 'Compliance & Licensing', 230, true),
  ('facility_review_facilityAnimalCareLicenseExpiry', 'facility_review', 'Facility Review Agent', 'facilityAnimalCareLicenseExpiry', 'Animal care license expiry date', 'Month / year.', 'text', 'June 2026', true, NULL, 'facility_review_compliance', 'Compliance & Licensing', 231, true),
  ('facility_review_facilityLastMunicipalInspection', 'facility_review', 'Facility Review Agent', 'facilityLastMunicipalInspection', 'Date of last municipal inspection', 'Month / year.', 'text', 'September 2025', true, NULL, 'facility_review_compliance', 'Compliance & Licensing', 232, true),
  ('facility_review_facilityLastInspectionOutcome', 'facility_review', 'Facility Review Agent', 'facilityLastInspectionOutcome', 'Outcome of last inspection', NULL, 'text', 'Passed - no violations', true, NULL, 'facility_review_compliance', 'Compliance & Licensing', 233, true),
  ('facility_review_facilityRegulatoryItems', 'facility_review', 'Facility Review Agent', 'facilityRegulatoryItems', 'Are there any outstanding violations, open permits, or unresolved regulatory items?', 'List each item. If none, write None.', 'textarea', 'None', true, NULL, 'facility_review_compliance', 'Compliance & Licensing', 234, true),
  ('facility_review_facilityRecentCapex', 'facility_review', 'Facility Review Agent', 'facilityRecentCapex', 'List all major capital expenditures made in the last 3 years.', 'Include item, year, and approximate cost.', 'textarea', 'New grooming tables, 2023, $4,200', true, NULL, 'facility_review_capex', 'Capital Expenditure History & Outlook', 240, true),
  ('facility_review_facilityExpectedCapex', 'facility_review', 'Facility Review Agent', 'facilityExpectedCapex', 'Are there any items expected to require capital investment in the next 1-3 years?', NULL, 'textarea', 'HVAC replacement likely within 2 years. Outdoor turf resurfacing anticipated.', true, NULL, 'facility_review_capex', 'Capital Expenditure History & Outlook', 241, true),
  ('facility_review_facilityReviewNotes', 'facility_review', 'Facility Review Agent', 'facilityReviewNotes', 'Additional facility notes', 'Optional context the structured answers and photos may not show.', 'textarea', 'Recent renovations, deferred maintenance, drainage issues, HVAC notes, odor/noise concerns...', false, NULL, 'facility_review_capex', 'Capital Expenditure History & Outlook', 242, true),

  ('professional_advisors_professionalAdvisorsList', 'professional_advisors', 'Professional Advisors Agent', 'professionalAdvisorsList', 'Professional advisors list', 'One advisor per line. Use: Role | Name | Company | Email | Phone | Notes.', 'textarea', 'Accountant | Jane Smith | Smith CPA | jane@example.com | 555-123-4567 | Handles tax filings\nLawyer | John Lee | Lee Law | john@example.com | 555-222-3333 | Lease counsel', false, NULL, 'professional_advisors', 'Professional Advisors Inputs', 300, true),

  ('vendor_directory_vendorDirectoryList', 'vendor_directory', 'Software & Vendors Agent', 'vendorDirectoryList', 'Software and vendor list', 'Two options to provide this information: 1. fill in the form below; 2. provide the information in an Excel file. Please note that we have provided a downloadable Excel template as a reference if required.', 'textarea', 'Gingr | Gingr | Booking/POS | 3600 | Active | unknown | Owner Only | Booking and customer records\nQuickBooks | Intuit | Accounting | 900 | Month-to-month | yes | Shared | Bookkeeping', false, NULL, 'vendor_directory', 'Software & Vendor Inputs', 310, true)
ON CONFLICT ("agentId", "fieldKey") DO UPDATE SET
  "agentName" = EXCLUDED."agentName",
  "label" = EXCLUDED."label",
  "description" = EXCLUDED."description",
  "inputType" = EXCLUDED."inputType",
  "placeholder" = EXCLUDED."placeholder",
  "required" = EXCLUDED."required",
  "options" = EXCLUDED."options",
  "groupKey" = EXCLUDED."groupKey",
  "groupLabel" = EXCLUDED."groupLabel",
  "sortOrder" = EXCLUDED."sortOrder",
  "isActive" = EXCLUDED."isActive",
  "updatedAt" = CURRENT_TIMESTAMP;
